### ISSUE TITLE
Color palette given in the README?

### ISSUE THREAD

**Issue by dhruvkrishnavaid** [SNDST00M/starfall-visual-studio-code#34]
### Describe your question
What's the use of the color palette given the README.md?
Is it like that we can choose any one of those themes?

### Search tags, topics
#readme #color-palette

**Comment by SNDST00M** [comment]
It's mostly for two purposes:
- a color reference when users want to customise their own themes using a Starfall color
- internal tracking and dev reference

It does occur to me that it'll grow soon and is already out if scope to the README, so I will likely move it to its own file

**Comment by SNDST00M** [comment]
It occurs to me that users who are offline cannot access the color scheme if it's removed.
I think it'd be best to keep it there, and I'll be closing the issue unless you feel the question remains unanswered?
