### ISSUE TITLE
Error and warning squiggles not clearly visible.

### ISSUE THREAD

**Issue by chandan00761** [SNDST00M/starfall-visual-studio-code#40]
## 🌃 Feature Request

- [x] I'm using the latest version of `starfall-visual-studio-code` available.
- [x] I searched [existing issues][starfall-vscode-issues], open & closed. Yes, my feature request is new.

### Is your feature request related to a problem?
Error squiggles are not properly visible with `starfall` theme.

![image](https://user-images.githubusercontent.com/28469311/150800182-8bf75d1d-af85-4e89-b515-67eacbc3d6eb.png)

### Describe the solution you'd like
Maybe add a different color for warning and error squiggles or increase the contrast.

### Describe alternatives you've considered
None

[starfall-vscode-issues]: https://github.com/SNDST00M/starfall-visual-studio-code/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by SNDST00M** [comment]
Sure I can double the alpha value on those (half transparency). I'll post a new version today 12:00AM

**Comment by SNDST00M** [comment]
Update to 0.5.1 to resolve this. Thanks for reporting!
